bashed my head in

diff --git a/mage b/mage
--- a/mage
+++ b/mage
@@ -2,30 +2,30 @@
 
 # Shell script to convert files from graphviz DOT format to svg
 
+set -e
+
 if ! command -v dot >/dev/null; then
     printf "Graphviz not installed\n" >&2
     exit 127
 fi
 
+output_set=false
 
 POSITIONAL_ARGS=()
-output_set=false
-input_set=false
 
-while [[ $# -gt 0 ]]; do
-    case $1 in
+while [[ "$#" -gt 0 ]]; do
+    case "$1" in
     -o|--output)
         output_set=true
         output="$2"
         shift
         ;;
     -i|--input)
-        input_set=true
-        input="$2"     
+        input="$2"
         shift
         ;;
     *)
-        printf "Unknown argument: %s\n" $1 >&2
+        printf "Unknown argument: %s\n" "$1" >&2
         exit 1
         ;;
     esac
@@ -34,20 +34,15 @@ done
 
 set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters
 
-echo $input_set
-echo $output_set
 
-if [ $input_set = true ] && [ $output_set = true ]; then
-    dot -Tsvg -o "$output.svg" < "$input"
-    
-elif [ $input_set = true ]; then
-    dot -Tsvg -o /dev/stdout < "$input"
-    
-elif [ $output_set = true ]; then
-    dot -Tsvg -o "$output.svg" < /dev/stdin
-    
+if [ "$output_set" = true ]; then
+    # clean up the DOT and save it
+    nop $input > "generated/${output}.gv"
+
+    # Use the clean DOT to generate and save an svg
+    dot -Tsvg -o "generated/${output}.svg" < "generated/${output}.gv"
 else
-    dot -Tsvg -o /dev/stdout < /dev/stdin
-    
+    # save nothing and spit out the svg
+    nop $input | dot -Tsvg < /dev/stdin
 fi
 
